apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x4n4m2ww5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-hub/x4n4m2ww5-java-springboot-gitops